include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    public_member_api_docs: true
    always_use_package_imports: true
    avoid_print: true
    prefer_final_locals: true
    prefer_const_constructors: true
    unnecessary_lambdas: true
    cancel_subscriptions: true
    close_sinks: true
